---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 2m0s  # Check for updates every 2 minutes
  chart:
    spec:
      chart: podinfo
      version: '>=6.0.0'  # Use any version 6.0.0 or higher
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 30s  # Check for chart updates every 30 seconds
  targetNamespace: default
  timeout: 3m0s
  values:
    # Custom values for the Helm chart
    replicaCount: 2
    image:
      tag: "6.9.0"
    ui:
      color: "#34577c"
    resources:
      limits:
        cpu: "2"
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 64Mi
    # Add custom labels to all resources
    labels:
      app.kubernetes.io/name: podinfo
      app.kubernetes.io/instance: podinfo-prod
      app.kubernetes.io/managed-by: flux
      environment: production
      team: platform
      version: v1.0.0
