---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s  # Check for chart updates every 30 seconds
  url: https://stefanprodan.github.io/podinfo
