---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 2m0s  # Faster sync - every 2 minutes
  path: ./kustomize
  prune: true
  retryInterval: 30s  # Faster retries
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        - op: add
          path: /metadata/labels/app.kubernetes.io~1name
          value: podinfo
        - op: add
          path: /metadata/labels/app.kubernetes.io~1instance
          value: podinfo-prod
        - op: add
          path: /metadata/labels/app.kubernetes.io~1managed-by
          value: flux
        - op: add
          path: /metadata/labels/environment
          value: production
        - op: add
          path: /metadata/labels/team
          value: platform
        - op: add
          path: /metadata/labels/version
          value: v1.0.0
      target:
        kind: Deployment
        name: podinfo
