---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 2m0s  # Faster sync - every 2 minutes
  path: ./kustomize
  prune: true
  retryInterval: 30s  # Faster retries
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
  timeout: 3m0s
  wait: true
  commonLabels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/instance: podinfo-prod
    app.kubernetes.io/managed-by: flux
    environment: production
    team: platform
    version: v1.0.0
