---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s  # Check for changes every 30 seconds
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
