apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: efs-csi-driver
  namespace: kube-system
spec:
  values:
    controller:
      serviceAccount:
        annotations:
          gwcp.guidewire.com/created-by: pod-warrior
          gwcp.guidewire.com/maintained-by: pod-warrior
          gwcp.guidewire.com/tenant-name: quadrant-shared
          gwcp.guidewire.com/dept: GW-OPS
          gwcp.guidewire.com/version: 3.1.8
          gwcp.guidewire.com/app-name: aws-efs-csi-driver